composite axons - bug fixes and optimization
Hjorthmedh/Snudda pull request #375
Opened 2023-04-03 17:46 UTC by wthun

This contains bug fixes for the updated format for connectivity and some optimizations (lazy loading) to be able to run these faster.  

(There's also an option added to specify rotation maps as rotation vectors, similar to the way neuron rotations are specified, since this seems to give smaller a smaller error when rotating.)

2023-04-03 18:57 UTC, Hjorthmedh requested changes

2023-04-03 18:57 UTC, Hjorthmedh commented on snudda/detect/detect.py
> +            self.voxel_overflow_counter += voxel_overflow_ctr
Varför tab på slutet?

2023-04-03 18:57 UTC, Hjorthmedh commented on snudda/detect/detect.py
> +            print(f"\033[91mFound zero length dendrite segment in neuron_id {neuron_id}\033[0m")
Vad är detta för konstiga tecken?

2023-04-03 18:57 UTC, Hjorthmedh commented on snudda/neurons/neuron_morphology_extended.py
> +            if position is not None: # why????
Har för mig att det är något tillfälle när position eventuellt är None, tex om man inte bryr sig om positionen för att köra ett okopplat nätverk.

2023-04-03 18:57 UTC, Hjorthmedh commented on snudda/place/place.py
> +        self.morphology_data_cache = {}
Varför?

2023-04-03 18:57 UTC, Hjorthmedh commented on snudda/place/place.py
> +            [np.where(np.isnan(target_centres[:,0]))[0],
Finns det inte ett smartare sätt att göra detta?
Typ summera längs y-axeln, och sedan göra en np.where. För om det är np.nan någonstans på raden kommer summan bli NaN.

2023-04-04 06:40 UTC, wthun commented on snudda/detect/detect.py
> +            print(f"\033[91mFound zero length dendrite segment in neuron_id {neuron_id}\033[0m")
Röd färg för printouts, men tog bort dessa  nu för enhetlighetens skull

2023-04-04 06:52 UTC, wthun commented on snudda/place/place.py
> +            [np.where(np.isnan(target_centres[:,0]))[0],
Fixat

2023-04-04 07:49 UTC, Hjorthmedh approved these changes

2023-04-04 08:29 UTC, merged